### ISSUE TITLE
Incorrect work with headers and footers

### ISSUE THREAD

**Issue by andkulikov** [eyeem/RecyclerViewTools#24]
Hi.

With recycler view you can't save the view that you are going to use as a header(footer), because every time onCreateViewHolder called you should return a new viewholder with a new view inside. Reusing of views is no allowed, because, for example, there are can be more that one instance of the same item for crossfade animation. And it will crash.
https://code.google.com/p/android/issues/detail?id=172416

You can create something like a header factory. So you will be able create a new header view for every onCreateViewHolder call.

**Comment by ronaldoeyeem** [comment]
Hi @andkulikov,
I understand the issue you're pointing and I agree it's possible to crash because we only have the view supplied by the application to be used, **BUT** as pointed out on https://code.google.com/p/android/issues/detail?id=172416 this crash will happen only for a `change` type of animation:

> **change** animations requires creating two copies of a ViewHolder (old one fades out, new one fades in)

That means, for the crash to happen, developers using the library would have to call `wrapAdapter.notifyItemChanged(0)` (or  `wrapAdapter.notifyRangeChanged(0, 2)`and that is wrong coding for a couple reasons:
- on the library README it's directly instructed to developers to not call `notify_` methods on the wrapAdapter, but to call it directly on their implemented adater and let the library correctly offset positions. Meaning header and footer shouldn't receive a `notify_`.
- and changes to the header (or footer), should be operated directly on their views (basically mimicking ListView way of doing it). 

That's because the library was planned to isolate header and footer views from the view recycling mechanism by giving them unique `ITEM_ID` and `ITEM_VIEW_TYPE` to them.

For example: below is a pseudo-code for a header with text and background image that are subscribed to a data source (hence will "change"). Note that notifyItemChanged is not used.

``` Java
TextView headerText;
ImageView headerImg;
public void onCreate(Bundle savedInstanceState){
   super.onCreate(savedInstanceState);
   ... inflate layout, create adapter and wrapAdapter, setup recycler view
   View header = LayoutInflater.from(this).inflate(.... );
   headerText = (TextView)header.findViewById(R.id.text);
   headerImg = (ImageView)header.findViewById(R.id.image);
   wrapAdapter.addHeader(header);
}

public void onStart(){
   dataSource.subscribe(this);
}
public void onStop(){
   dataSource.unsubscribe(this);
}
public void onDataChanged(Data newData){
    headerText.setText(newData.title);
   Picasso.with(this).load(newData.url).into(headerImg);
}
```

I'll label this for now as `wontfix`, but if you disagree with the arguments, please, feel free to:
- provide a counter argument
- supply a reproducible minimal code
- make a pull request

**Comment by andkulikov** [comment]
Basically, I agree with you. It should be the only case for now. Only bad thing is that returning a new view is like a contract for onCreateViewHolder. So Google developers potentially can add more cases when they need to have two instances for a view for some reasons in the feature.

And the same situation here with the customView. 

I got your position. Main thing here is to keep all limitation in mind.

Thanks

**Comment by ronaldoeyeem** [comment]
@andkulikov those are valid points.
But I guess preemptive optimization that would generate such a big refactor and change of API (header factory) on the library side doesn't sound like something to go for.
But it's good to keep in mind the potential dangers of it, thanks for contributing.
